apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: nodejs-app
        image: 10.98.126.24:5000/repository/docker-repo/app:latest
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: app-secret
    
